# Site settings
title: 没有名字的博客
author: Priest Tomb
author_avatar: /images/header.jpg
description: 没有名字的博客
url: "https://priesttomb.github.io"
baseurl: ""
github_username: priesttomb
github_site_repo: priesttomb/priesttomb.github.io

# 代码高亮及markdown配置
highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge
  extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/

# 插件
plugins: [jekyll-paginate]

# 分页
paginate: 10
paginate_path: "/page/:num/"

# 访问记录
leancloud:
  enable: false
  app_id: xxx
  app_key: xxx

# firebase
firebase:
  enable: true
  project_id: my-jekyll-blog
  api_key: AIzaSyCZFEk_nCbqq2UKdS6RCDusZlyGNPknDPg
  sender_id: 814452624014
  app_id: 1:814452624014:web:0981e9e16b1a7aac

# 更新一下重新部署
