# Site settings
title: 没有名字的博客
author: Priest Tomb
author_avatar: /images/header.jpg
description: 没有名字的博客
url: "https://priesttomb.github.io"
baseurl: ""
github_username: priesttomb
github_site_repo: priesttomb/priesttomb.github.io


github_username: PriestTomb
zhihu_username: mu-xiao-mu-60
twitter_username: PriestTomb
my_email: Mxingzh@163.com

personal_label: 弱渣coder/爱好广泛无一专精

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


plugins: [jekyll-paginate]

# 分页
paginate: 10
paginate_path: "/page/:num/"
