# Site settings
title: 没有名字的博客
author: Priest Tomb
author_avatar: /images/header.jpg
description: 没有名字的博客
url: "https://priesttomb.github.io"
baseurl: ""
github_username: priesttomb
github_site_repo: priesttomb/priesttomb.github.io

# 社交信息
github_username: PriestTomb
zhihu_username: mu-xiao-mu-60
twitter_username: PriestTomb
my_email: Mxingzh@163.com

# 代码高亮及markdown配置
highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge
  extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/

# 插件
#plugins: [jekyll-paginate]
gems: [jekyll-paginate]

# 分页
paginate: 10
paginate_path: "/page/:num/"

# 访问记录
leancloud:
  enable: true
  app_id: sHOACpcLa8X13BWC7z1AFx3L-gzGzoHsz
  app_key: D6LrgfFtGUteAInLJqtfjtx5
